// <auto-generated />
namespace WebApiAngular.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mudanca_product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mudanca_product));
        
        string IMigrationMetadata.Id
        {
            get { return "201708152342590_mudanca_product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
